[package]
name = "sctpx"
version = "0.1.5"
authors = ["FanHui <hui.fan@mail.ru>"]
edition = "2018"
description = "A simple and friendly SCTP wrapper."
keywords = ["sctp", "socket", "net"]
categories = ["network-programming"]
license = "MIT"
homepage = "https://gitee.com/kt10/sctpx"
repository = "https://gitee.com/kt10/sctpx.git"

[dependencies]
nix = "0.18"
libc = "0.2"
ruc = { git = "https://gitee.com/kt10/ruc" , branch = "master" }

[features]
default = ["client", "server"]
client = []
server = []
